services:
  service1:
    build: 
      context: ./service1
    ports:
      - "8199:8199"
    depends_on: [service2, storage]
    networks: [private, public]
    environment:
      PORT: 8199
      SERVICE2_URL: http://service2:8198
      STORAGE_URL:  http://storage:8197
      VSTORAGE_PATH: /vstorage
    volumes:
      - ./vstorage:/vstorage

  service2:
    build: 
      context: ./service2
    networks: [private]
    environment:
      PORT: 8198
      STORAGE_URL:  http://storage:8197
      VSTORAGE_PATH: /vstorage
    volumes:
      - ./vstorage:/vstorage

  storage:
    build: 
      context: ./storage
    networks: [private]
    environment:
      PORT: 8197
      LOG_PATH: /data/storage.log
    volumes:
      - storage:/data

networks:
  private:
    driver: bridge
    internal: true
  public:
    driver: bridge
  

volumes:
  storage: {}